[project]
name = "orjson"
repository = "https://github.com/ijl/orjson"

[build-system]
build-backend = "maturin"
requires = ["maturin>=0.8.1,<0.10"]

[tool.maturin]
manylinux = "off"
sdist-include = ["Cargo.lock", "json/**/*"]
strip = "on"

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
