name: manylinux

inputs:
  arch:
    required: true
  interpreter:
    required: true
  features:
    required: true
  compatibility:
    required: true
  publish:
    required: true

runs:
  using: "composite"
  steps:

    - name: Build and test
      shell: bash
      run: |
        set -eou pipefail

        mkdir dist

        export PYTHON="${{ inputs.interpreter }}"
        if [[ "${PYTHON}" == *t ]]; then
          export PYTHON_PACKAGE="$(echo ${PYTHON} | sed 's/.$//')-freethreading"
        else
          export PYTHON_PACKAGE="${PYTHON}"
        fi

        export TARGET="${{ inputs.arch }}-unknown-linux-gnu"
        export PATH="$PWD/.venv:$HOME/.cargo/bin:$PATH"

        dnf copr enable -y @fedora-llvm-team/llvm20

        ./script/install-fedora

        source "${VENV}/bin/activate"

        maturin build --release --strip \
          --features="${{ inputs.features }}" \
          --compatibility="${{ inputs.compatibility }}" \
          --interpreter="${PYTHON}" \
          --target="${TARGET}"

        uv pip install ${CARGO_TARGET_DIR}/wheels/orjson*.whl

        export PYTHONMALLOC="debug"
        pytest -v test
        ./integration/run thread
        ./integration/run http
        ./integration/run init

        cp ${CARGO_TARGET_DIR}/wheels/orjson*.whl dist
