name: lint
on: push
env:
  FORCE_COLOR: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=default -y
    - run: pip install -U "ruff>=0.14,<0.15" "mypy==1.18.2"

    - uses: actions/checkout@v5

    - run: cargo fmt
    - run: ./script/lint

    - run: git diff --exit-code
