name: unusual
on: push
env:
  FORCE_COLOR: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
jobs:

  unusual:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        cfg: [
          { rust: "1.85", python: "3.15", version_check: "1" },
          { rust: "1.85", python: "3.14", version_check: "0" },
          { rust: "1.85", python: "3.9", version_check: "0" },
        ]
    steps:
    - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain ${{ matrix.cfg.rust }} --profile minimal -y

    - uses: actions/setup-python@v5
      with:
        python-version: '${{ matrix.cfg.python }}'
        allow-prereleases: true

    - run: python -m pip install --user --upgrade pip "maturin>=1,<2" wheel

    - uses: actions/checkout@v4

    - name: build
      run: |
        PATH="$HOME/.cargo/bin:$PATH" UNSAFE_PYO3_SKIP_VERSION_CHECK="${{ matrix.cfg.version_check }}" \
          maturin build \
          --profile=dev \
          --interpreter python${{ matrix.cfg.python }} \
          --target=x86_64-unknown-linux-gnu

    - run: python -m pip install --user target/wheels/orjson*.whl
    - run: python -m pip install --user -r test/requirements.txt -r integration/requirements.txt

    - run: pytest -s -rxX -v test
      timeout-minutes: 4
      env:
        PYTHONMALLOC: "debug"

    - run: ./integration/run thread
      timeout-minutes: 2

    - run: ./integration/run http
      timeout-minutes: 2

    - run: ./integration/run init
      timeout-minutes: 2
